-- MySQL Script generated by MySQL Workbench
-- 12/10/17 19:15:28
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_alumnos_universidad
-- -----------------------------------------------------
-- base de datos para el proyecto del curso de taller de innovación tecnológica.
CREATE SCHEMA IF NOT EXISTS `bd_alumnos_universidad` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_alumnos_universidad` ;

-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`PERSONA` (
  `idPERSONA` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `ap_paterno` VARCHAR(50) NOT NULL,
  `ap_materno` VARCHAR(50) NOT NULL,
  `dni` CHAR(8) NOT NULL,
  `f_nacimiento` DATE NOT NULL,
  `email` VARCHAR(150) NULL,
  `telf` VARCHAR(15) NULL,
  `cel` VARCHAR(9) NULL,
  `direccion` VARCHAR(100) NULL,
  `foto` MEDIUMBLOB NULL,
  `sexo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idPERSONA`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`CURSO` (
  `idCURSO` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idCURSO`),
  UNIQUE INDEX `nombre_curso_UNIQUE` (`nombre_curso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`NOMBRE_CICLO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`NOMBRE_CICLO` (
  `idNOMBRE_CICLO` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciclo` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idNOMBRE_CICLO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`FACULTAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`FACULTAD` (
  `idFACULTAD` INT NOT NULL AUTO_INCREMENT,
  `nombre_facu` VARCHAR(120) NOT NULL,
  `f_creacion` DATE NOT NULL,
  PRIMARY KEY (`idFACULTAD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`CARRERA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`CARRERA` (
  `idCARRERA` INT NOT NULL AUTO_INCREMENT,
  `nombre_carrera` VARCHAR(120) NOT NULL,
  `f_creacion` DATE NOT NULL,
  `logo` MEDIUMBLOB NULL,
  `id_facultad` INT NOT NULL,
  `id_ciclo_max` INT NOT NULL,
  PRIMARY KEY (`idCARRERA`),
  INDEX `fk_CARRERA_FACULTAD1_idx` (`id_facultad` ASC),
  INDEX `fk_CARRERA_NOMBRE_CICLO1_idx` (`id_ciclo_max` ASC),
  CONSTRAINT `fk_CARRERA_FACULTAD1`
    FOREIGN KEY (`id_facultad`)
    REFERENCES `bd_alumnos_universidad`.`FACULTAD` (`idFACULTAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARRERA_NOMBRE_CICLO1`
    FOREIGN KEY (`id_ciclo_max`)
    REFERENCES `bd_alumnos_universidad`.`NOMBRE_CICLO` (`idNOMBRE_CICLO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`DOCENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`DOCENTE` (
  `idDOCENTE` INT NOT NULL AUTO_INCREMENT,
  `f_ingreso` DATE NOT NULL,
  `codigo_docente` CHAR(10) NOT NULL,
  `id_persona` INT NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDOCENTE`),
  INDEX `fk_DOCENTE_PERSONA1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_DOCENTE_PERSONA1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `bd_alumnos_universidad`.`PERSONA` (`idPERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`ALUMNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`ALUMNO` (
  `idALUMNO` INT NOT NULL AUTO_INCREMENT,
  `codigo_universitario` CHAR(10) NOT NULL,
  `f_ingreso` DATE NOT NULL,
  `id_persona` INT NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idALUMNO`),
  UNIQUE INDEX `codigo_universitario` (`codigo_universitario` ASC),
  INDEX `fk_ALUMNO_PERSONA1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_ALUMNO_PERSONA1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `bd_alumnos_universidad`.`PERSONA` (`idPERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`PLAN_ESTUDIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`PLAN_ESTUDIOS` (
  `idPLAN_ESTUDIOS` INT NOT NULL AUTO_INCREMENT,
  `nombre_plan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPLAN_ESTUDIOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`CURSO_DE_PLAN_ESTUDIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`CURSO_DE_PLAN_ESTUDIOS` (
  `idCURSO_DE_PLAN_ESTUDIOS` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_carrera` INT NOT NULL,
  `id_plan_estudios` INT NOT NULL,
  `id_nombre_ciclo` INT NOT NULL,
  `creditos` DOUBLE NOT NULL,
  PRIMARY KEY (`idCURSO_DE_PLAN_ESTUDIOS`),
  INDEX `fk_CURSO_CARRERA_CARRERA1_idx` (`id_carrera` ASC),
  INDEX `fk_CURSO_CARRERA_CURSO1_idx` (`id_curso` ASC),
  INDEX `fk_CURSO_CARRERA_NOMBRE_CICLO1_idx` (`id_nombre_ciclo` ASC),
  INDEX `fk_CURSO_CARRERA_PLAN_ESTUDIOS1_idx` (`id_plan_estudios` ASC),
  CONSTRAINT `fk_CURSO_CARRERA_CARRERA1`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `bd_alumnos_universidad`.`CARRERA` (`idCARRERA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_CARRERA_CURSO1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_alumnos_universidad`.`CURSO` (`idCURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_CARRERA_NOMBRE_CICLO1`
    FOREIGN KEY (`id_nombre_ciclo`)
    REFERENCES `bd_alumnos_universidad`.`NOMBRE_CICLO` (`idNOMBRE_CICLO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_CARRERA_PLAN_ESTUDIOS1`
    FOREIGN KEY (`id_plan_estudios`)
    REFERENCES `bd_alumnos_universidad`.`PLAN_ESTUDIOS` (`idPLAN_ESTUDIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`CICLO_ACADEMICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`CICLO_ACADEMICO` (
  `idCICLO_ACADEMICO` INT NOT NULL AUTO_INCREMENT,
  `f_inicio` DATE NOT NULL,
  `f_fin` DATE NULL,
  PRIMARY KEY (`idCICLO_ACADEMICO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`CURSO_ABIERTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`CURSO_ABIERTO` (
  `idCURSO_ABIERTO` INT NOT NULL AUTO_INCREMENT,
  `id_ciclo_academico` INT NOT NULL,
  `id_docente` INT NOT NULL,
  `id_curso_de_plan_estudios` INT NOT NULL,
  PRIMARY KEY (`idCURSO_ABIERTO`),
  INDEX `fk_CURSO_ABIERTO_DOCENTE1_idx` (`id_docente` ASC),
  INDEX `fk_CURSO_ABIERTO_CICLO_ACADEMICO1_idx` (`id_ciclo_academico` ASC),
  INDEX `fk_CURSO_ABIERTO_CURSO_CARRERA1_idx` (`id_curso_de_plan_estudios` ASC),
  CONSTRAINT `fk_CURSO_ABIERTO_DOCENTE1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `bd_alumnos_universidad`.`DOCENTE` (`idDOCENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_ABIERTO_CICLO_ACADEMICO1`
    FOREIGN KEY (`id_ciclo_academico`)
    REFERENCES `bd_alumnos_universidad`.`CICLO_ACADEMICO` (`idCICLO_ACADEMICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_ABIERTO_CURSO_CARRERA1`
    FOREIGN KEY (`id_curso_de_plan_estudios`)
    REFERENCES `bd_alumnos_universidad`.`CURSO_DE_PLAN_ESTUDIOS` (`idCURSO_DE_PLAN_ESTUDIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`MATRICULA_CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`MATRICULA_CURSO` (
  `idMATRICULA_CURSO` INT NOT NULL AUTO_INCREMENT,
  `id_alumno` INT NOT NULL,
  `id_curso_abierto` INT NOT NULL,
  `ec1` DOUBLE NULL,
  `ep1` DOUBLE NULL,
  `ed1` DOUBLE NULL,
  `ec2` DOUBLE NULL,
  `ep2` DOUBLE NULL,
  `ed2` DOUBLE NULL,
  `ec3` DOUBLE NULL,
  `ep3` DOUBLE NULL,
  `ed3` DOUBLE NULL,
  `ec4` DOUBLE NULL,
  `ep4` DOUBLE NULL,
  `ed4` DOUBLE NULL,
  PRIMARY KEY (`idMATRICULA_CURSO`),
  INDEX `fk_MATRICULA_CURSO_ALUMNO1_idx` (`id_alumno` ASC),
  INDEX `fk_MATRICULA_CURSO_CURSO_ABIERTO1_idx` (`id_curso_abierto` ASC),
  CONSTRAINT `fk_MATRICULA_CURSO_ALUMNO1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `bd_alumnos_universidad`.`ALUMNO` (`idALUMNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATRICULA_CURSO_CURSO_ABIERTO1`
    FOREIGN KEY (`id_curso_abierto`)
    REFERENCES `bd_alumnos_universidad`.`CURSO_ABIERTO` (`idCURSO_ABIERTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`CLASE_PROGRAMADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`CLASE_PROGRAMADA` (
  `idCLASE_PROGRAMADA` INT NOT NULL AUTO_INCREMENT,
  `tema_de_clase` VARCHAR(200) NOT NULL,
  `id_curso_abierto` INT NOT NULL,
  PRIMARY KEY (`idCLASE_PROGRAMADA`),
  INDEX `fk_CLASE_PROGRAMADA_CURSO_ABIERTO1_idx` (`id_curso_abierto` ASC),
  CONSTRAINT `fk_CLASE_PROGRAMADA_CURSO_ABIERTO1`
    FOREIGN KEY (`id_curso_abierto`)
    REFERENCES `bd_alumnos_universidad`.`CURSO_ABIERTO` (`idCURSO_ABIERTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`ASISTENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`ASISTENCIA` (
  `idASISTENCIA` INT NOT NULL AUTO_INCREMENT,
  `id_matricula_curso` INT NOT NULL,
  `id_clase_programada` INT NOT NULL,
  PRIMARY KEY (`idASISTENCIA`),
  INDEX `fk_ASISTENCIA_MATRICULA_CURSO1_idx` (`id_matricula_curso` ASC),
  INDEX `fk_ASISTENCIA_CLASE_PROGRAMADA1_idx` (`id_clase_programada` ASC),
  CONSTRAINT `fk_ASISTENCIA_MATRICULA_CURSO1`
    FOREIGN KEY (`id_matricula_curso`)
    REFERENCES `bd_alumnos_universidad`.`MATRICULA_CURSO` (`idMATRICULA_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASISTENCIA_CLASE_PROGRAMADA1`
    FOREIGN KEY (`id_clase_programada`)
    REFERENCES `bd_alumnos_universidad`.`CLASE_PROGRAMADA` (`idCLASE_PROGRAMADA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`AULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`AULA` (
  `idAULA` INT NOT NULL AUTO_INCREMENT,
  `tipo` CHAR(1) NOT NULL,
  `piso` TINYINT(1) NOT NULL,
  `id_carrera` INT NOT NULL,
  PRIMARY KEY (`idAULA`),
  INDEX `fk_AULA_CARRERA1_idx` (`id_carrera` ASC),
  CONSTRAINT `fk_AULA_CARRERA1`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `bd_alumnos_universidad`.`CARRERA` (`idCARRERA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_alumnos_universidad`.`HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_alumnos_universidad`.`HORARIO` (
  `idHORARIO` INT NOT NULL AUTO_INCREMENT,
  `dia` CHAR(1) NOT NULL,
  `horas` INT NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `id_aula` INT NOT NULL,
  `id_curso_abierto` INT NOT NULL,
  PRIMARY KEY (`idHORARIO`),
  INDEX `fk_HORARIO_AULA1_idx` (`id_aula` ASC),
  INDEX `fk_HORARIO_CURSO_ABIERTO1_idx` (`id_curso_abierto` ASC),
  CONSTRAINT `fk_HORARIO_AULA1`
    FOREIGN KEY (`id_aula`)
    REFERENCES `bd_alumnos_universidad`.`AULA` (`idAULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HORARIO_CURSO_ABIERTO1`
    FOREIGN KEY (`id_curso_abierto`)
    REFERENCES `bd_alumnos_universidad`.`CURSO_ABIERTO` (`idCURSO_ABIERTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
